### ISSUE TITLE
Barcode is invalid, migrations fail

### ISSUE THREAD

**Issue by ampodobas** [thecodework/two-factor-authentication#34]
This package works very well for intercepting the auth request after login and has great setup instructions. 

However, two issues for a fresh install using the instructions provided on this repo:

(1) I keep getting "QR code is invalid" (or similar) on both Google Auth and Authy. In case this additional info helps, the secret key generated in the user's table upon a fresh install seems to be adding an arbitrary number of equals signs at the end: "MFWGK6CAOVZXA4TPORSWG2BOMNXW2===".

(2) A RequiredFields error is thrown for migrations: [2017-04-01 17:14:40] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'RequiredFields' not found in /Users/[...redacted...]

**Comment by imrealashu** [comment]
@ampodobas thank you for the detailed error message. Can you show me the config file ?

**Comment by ampodobas** [comment]
@imrealashu: 

- I followed the instructions on this page precisely: http://imrealashu.in/code/laravel/two-factor-authentication-in-laravel/. 

- When I did a composer require for your project, the version entry was: 
`"thecodework/two-factor-authentication":` "^0.1.3",`

- There also seems to be an issue with the ajax() request conditional. It worked after I amended the vendor file from ` if ($request - ajax()) {` to  `if ($request ->ajax()) {` in TwoFactorAuthenticationController.php.

**Comment by imrealashu** [comment]
I'd suggest use version 0.1.2 for now, I'm working on #13 and it is currently in WIP. I'll solve it at the earliest.

**Comment by ampodobas** [comment]
@imrealashu: many thanks. I've tried a number of other two-factor auth packages for an InfoSec monitoring tool I'm developing using Laravel and none intercepted the authentication request upon a successful login like your's did. I look forward to using it, and I appreciate the quick follow-up.

**Comment by imrealashu** [comment]
@ampodobas sure, I'll resolve those issues and put an stable update soon. Meanwhile if you spot any error or bug using version `0.1.2` do create an issue, I'll try to resolve it asap.

**Comment by imrealashu** [comment]
@ampodobas I've fixed the issue and will put an update soon. The actual problem was the migration which further failing generating valid barcode. Thank you for trying it out and creating the issue. Closing it for now, will notify you once I put an update.

**Comment by imrealashu** [comment]
@ampodobas I've released an update `0.1.4`, it tested and can be added in your project. However `0.1.5` version is releasing anytime soon today which adds a new feature to specify your User model and table gives more flexibility to projects where user have multiple authentication.
I look forward to your review and feedback. Thank you.

**Comment by ampodobas** [comment]
@imrealashu: 

(1) The same issue about the invalid barcodes is persisting:
![img_0205](https://cloud.githubusercontent.com/assets/1124377/24596421/0da543b0-17f4-11e7-960d-18b99e1a5028.PNG)

(2) The multiple equals signs (which I've never seen in any secret key before) are still being appended to the typically "normal," alpha-numeric secret key. I think solving how the secret key is generated and inserted should be dealt with first. If you want me to help test anything, I would benefit from it because I want to use this package as quickly as possible in my project. 
![image](https://cloud.githubusercontent.com/assets/1124377/24596442/313098fc-17f4-11e7-97c5-9f38d6bda380.png)

**Comment by imrealashu** [comment]
I don't think that's an issue and I'll explain it to you asap. meanwhile Did you try removing the package completely and reinstalling it again ?

**Comment by imrealashu** [comment]
I've just checked this using Authy, and it turned out to be not working using that. However I'm not facing any issue usng Google Authenticator. I'll work on it and update it asap.

**Comment by imrealashu** [comment]
`0.1.6` is tested and working using Google Authenticator as well as Authy with default configuration.
