### ISSUE TITLE
FatalErrorException in TwoFactorAuthenticationServiceProvider.php line 43

### ISSUE THREAD

**Issue by maorkavod** [thecodework/two-factor-authentication#41]
Hello,
i just install your package and  got this error: 

FatalErrorException in TwoFactorAuthenticationServiceProvider.php line 43:
syntax error, unexpected ':', expecting ';' or '{'

can you please help me with this? 
thanks!

**Comment by imrealashu** [comment]
which version you're using? 1.6 ?

**Comment by maorkavod** [comment]
"thecodework/two-factor-authentication": "^0.1.6"

**Comment by imrealashu** [comment]
I think it is issue with the PHP version. Which PHP version you're using ?

**Comment by maorkavod** [comment]
PHP 7.0.18-1+deb.sury.org~trusty+1 (cli) (built: Apr 11 2017 15:08:38) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18-1+deb.sury.org~trusty+1, Copyright (c) 1999-2017, by Zend Technologies

**Comment by imrealashu** [comment]
PHP version is fine, could you go to the source and change few lines ?
`vendor/thecodework/two-factor-authentication/src/TwoFactorAuthenticationServiceProvider.php` 
> Use `public static function determineTwoFAModel()` instead of `public static function determineTwoFAModel(): string`

And

>in the same file, `public static function getTwoFAModelInstance()` instead of `public static function getTwoFAModelInstance(): Model`

let me know if that works aur any new error messages.

**Comment by maorkavod** [comment]
its working now, thanks :)
i dont know this code syntax : 

determineTwoFAModel(): string
function getTwoFAModelInstance(): Model

what dose its mean?

**Comment by imrealashu** [comment]
So I would suggest you to check your php7 installation. PHP can be installed in different versions on a system. Also the CLI version can certainly be a different one than the one loaded as a module into an http server. So in short your cli version is different. Please uninstall php completely and reinstall it. or try to run your app using laravel artisan helper command `php artisan serve`

**Comment by maorkavod** [comment]
there where more functions like that on TwoFactorAuthenticationController.php
last one i dont know how to fix is this : 


FatalErrorException in TwoFactorAuthenticationController.php line 183:
syntax error, unexpected '?'

**Comment by imrealashu** [comment]
Please refer to this comment https://github.com/thecodework/two-factor-authentication/issues/41#issuecomment-294351449 and check your php loaded module and cli version are same?

**Comment by maorkavod** [comment]
checking it , right now

**Comment by maorkavod** [comment]
the versions are the same php 7

**Comment by imrealashu** [comment]
did you try running your project using `php artisan serve` ?

**Comment by maorkavod** [comment]
you are right! the loaded php it is different i saw it only on phpinfo();
i will fix this right now, and update.. thank you! 👍

**Comment by imrealashu** [comment]
you're most welcome @maorkavod 👍
