### ISSUE TITLE
Token is not valid?

### ISSUE THREAD

**Issue by maorkavod** [thecodework/two-factor-authentication#44]
Hello again.
i have installed the package and everything works great!
but it seems that i cant make a login, every time i got the same message.
"Token is not valid"
Do i need to sync my server time to some time zone? 
why this could happen?

**Comment by imrealashu** [comment]
which client application you're using? Google Authenticator or Authy?

**Comment by maorkavod** [comment]
I have tried them both.
First with Authy than Google 2fa.
Should i revers migrate and try again with a specific Application?  

My server clock is sync to : 
/usr/share/zoneinfo/Asia/Yerevan

**Comment by imrealashu** [comment]
Should be timezone issue.. In the client application there is an option to sync server time, did you try that?

**Comment by maorkavod** [comment]
When i type the command "date"
Im getting : Mon Apr 17 16:08:14 AMT 2017
Which is sync perfectly to my pc and my Mobile phone.

this is OK? to which timezone i need sync my server?

**Comment by imrealashu** [comment]
I prefer using UTC though... and what timezone you've defined in your laravel application ? `config/app.php` file..

**Comment by imrealashu** [comment]
And in Google authenticator there is an option to sync device time with the server time. `Settings->Time Correction For Codes -> Sync Now` did you do that?  did you see any error there?

**Comment by imrealashu** [comment]
make sure your server synced with ntp (Network Time Protocol). try hitting `ntpdate` on the server. if `ntpdate` not installed do these steps to synchronise server time.
```bash 
sudo apt-get update
sudo apt-get install ntpdate
sudo ntpdate -s time.nist.gov```

**Comment by maorkavod** [comment]
Ok so i set the time zone in laravel to UTC
also sync my server with ntpdate
also sync time with google application. 
still no luck, "Token is not valid" 

i will continue to test it and find the problem. 
its weird, its should work, all the time zone set right.

**Comment by imrealashu** [comment]
after these steps try to re-generate barcode and re-scan it.

**Comment by maorkavod** [comment]
Still the same, no luck.
everything is utc and synced.

this is from my phpinfo : 

date

date/time support	enabled
"Olson" Timezone Database Version	0.system
Timezone Database	internal
Default timezone	UTC
Directive	Local Value	Master Value
date.default_latitude	31.7667	31.7667
date.default_longitude	35.2333	35.2333
date.sunrise_zenith	90.583333	90.583333
date.sunset_zenith	90.583333	90.583333
date.timezone	UTC	UTC


app config : 
 'timezone' => 'UTC',

server date: 
Mon Apr 17 13:01:16 UTC 2017

**Comment by imrealashu** [comment]
that's strange. I'm reproducing it on my server. I'll update here asap.

**Comment by maorkavod** [comment]
thank you :)

**Comment by imrealashu** [comment]
Hey @maorkavod I reproduced that error and synchronised my datetime using NTP but that didn't work. However I tweaked the configuration little bit and I think the below configuration should work fine for both GA and Authy.
```php
algorithm => 'sha512',
number_of_digits => 6,
period => 10

Let me know if that works for you.

**Comment by maorkavod** [comment]
Sorry but still the same result for both applications :-/

**Comment by imrealashu** [comment]
That's strange. Well in that case I'll look into it and figure out what's going wrong, we'll try to fix asap.

**Comment by maorkavod** [comment]
thanks

**Comment by maorkavod** [comment]
This is working now only for Google Authenticator, which is enough me,
i just remove from the constructor of TOTP inside function "setupTwoFactorAuthentication" and kept the secret : 
 public function setupTwoFactorAuthentication(Request $request)
    {
        $this->updateUserWith2FAGeneratedKey();
        $user = $this->getUser();
        $totp = new TOTP(
            config('2fa-config.account_name'),
            $user->two_factor_secret_key
            // config('2fa-config.period'),
            // config('2fa-config.digest_algorithm'),
            // config('2fa-config.number_of_digits')
        );
        
        $barcode = $totp->getQrCodeUri();

        if ($request->ajax()) {
            return $barcode;
        }

        return view('2fa::setup', compact('barcode', 'user'));
    }

**Comment by physio** [comment]
I have the same problem. can you help me?

**Comment by maorkavod** [comment]
Sure, here is my config and view : 

```PHP 
/*
     * Specify redirect url after when token authentication
     * is successfull.
     */
    'redirect_to' => '/home',

    /*
     * Routes
     * Change the routes if your existing routes
     * conflicts with existing routes. or for
     * any customization.
     */
    'setup_2fa'   => 'setup-2fa',
    'enable_2fa'  => 'enable-2fa',
    'disable_2fa' => 'disable-2fa',

    /*
     * Account name which will be used as label to show on
     * authenticator mobile application.
     */
    'account_name' => 'XXXXX',

    /*
     * Currntly Support 'Sha1'
     * The library works with the Google Authenticator application
     * for iPhone and Android. Google only supports SHA-1 digest algorithm,
     * 30 second period and 6 digits OTP. Other values for these parameters
     * are ignored by the Google Authenticator application.
     */
    'digest_algorithm' => 'sha1',

    /*
     * Size of Base32 encoded secret key.
     * Default 6 Works with GA and Authy.
     */
    'number_of_digits' => 6,

    /*
     * The Number of Seconds the code will be valid.
     * Default 30.
     */
    'period' => 30,

    /*
     * Explitcitly Define Table name for the model.
     */
    'table' => 'users',

    /*
     * User Model
     * By Default `\App\User` Model is defined.
     */
    'model' => '\App\User',
```

Also my view : 

```
@if($user->is_two_factor_enabled)
                    <form class="form-horizontal" role="form" method="POST" action="{{ url('/disable-2fa') }}">
                    @else
                    <form class="form-horizontal" role="form" method="POST" action="{{ url('/enable-2fa') }}">
                    @endif
                        {{ csrf_field() }}
                        {{-- <label for="email" class="col-md-4 control-label text-center">Secret Key</label> --}}
                        <div class="form-group text-center">
                        @if(! $user->is_two_factor_enabled)
                            @if(!Session::has('refreshed'))
                                {{ Session::put('refreshed',true) }}
                                <script>location.reload();</script>
                            @else
                                 {{Session::forget('refreshed')}}
                            @endif
                            
                        <h4> {{trans('auth.please_scan_code')}} <b>{{trans('auth.enable_button')}}</b></h4>
                            <img src="{{ $barcode }}" />
                        @endif
                        </div>
                        <div class="form-group text-center">
                            <div class="col-md-8 col-md-offset-2">
                            @if($user->is_two_factor_enabled)
                                <button type="submit" class="btn btn-danger">
                                   {{trans('auth.disable_2fa')}}
                                </button>
                            @else
                                <button type="submit" class="btn btn-success">
                                   {{trans('auth.enable_2fa')}}
                                </button>
                            @endif
                            </div>
                        </div>
                    </form>
```

**Comment by physio** [comment]
Now work fine ;-) 
it was a csrf_field problem?

**Comment by maorkavod** [comment]
Im not sure,
it started to work when i refresh the page, the barcode somehow not sync at the first page load,
only after i refresh the page as you can see in the code above..

**Comment by duauday** [comment]
Hi team, 
How to generate QR code for AuthY
