### ISSUE TITLE
upgrade to laravel 5.5 bug - "Class 'Base32\Base32' not found"

### ISSUE THREAD

**Issue by maorkavod** [thecodework/two-factor-authentication#45]
Hello, sinse i update to laravel 5.5 im getting this error with this packeg ; 

Class 'Base32\Base32' not found

Symfony\Component\Debug\Exception\FatalThrowableError 
…/vendor/thecodework/two-factor-authentication/src/Http/Controllers/TwoFactorAuthenticationController.php152

```PHP
private function base32EncodedString($length = 30):
    string
    {
        return Base32::encode($this->strRandom($length));
    }
```

**Comment by imrealashu** [comment]
Hey @maorkavod 
I haven't tested it with laravel 5.5 so in coming week I'd be able to work on this and make it laravel 5.5 compatible.

**Comment by nclifton** [comment]
Hi,
I'm on Laravel 5.4.36 for my current project, and I also do not have a Base32\Base32 class in my libraries. I'm going to see what I can do with ParagonIE\ConstantTime\Base32 instead ... https://github.com/paragonie/constant_time_encoding

**Comment by maorkavod** [comment]
Hello, 
I fixed this issue just by adding this to my laravel composer : 

"christian-riesen/base32": "^1.3"

**Comment by imrealashu** [comment]
I'd suggest "paragonie/constant_time_encoding" instead which is designed to prevent timing attacks.
