### ISSUE TITLE
Extends Controller class from default new project namespace

### ISSUE THREAD

**Issue by nclifton** [thecodework/two-factor-authentication#46]
Hi,
Minor complaint.

\Thecodework\TwoFactorAuthentication\Http\Controllers\TwoFactorAuthenticationController

I have renamed my Laravel project's namespace, and so the Controller class TwoFactorAuthenticationController extends is no longer found in the \App\Http\Controllers namespace.

So either I have to rename my project namespace back to "App" or I have to make a copy of the TwoFactorAuthenticationController in my project's controller directory with my namespace.

Just something people need to be aware of if they are using their own namespace.

**Comment by imrealashu** [comment]
Thanks for noticing that. I'd look into it at the earliest and fix the issue.

**Comment by nclifton** [comment]
Thanks Ashish

**Comment by nclifton** [comment]
If I do my own controller, I have to do my own routes too.

**Comment by imrealashu** [comment]
@nclifton Apologies for delay. That's been fixed in version `>=0.1.7`
