### ISSUE TITLE
two_factor_provisioned_uri field not found

### ISSUE THREAD

**Issue by Destronom** [thecodework/two-factor-authentication#50]
Hey, currently there is an issue in the new version 0.1.7

the new field "two_factor_provisioned_uri" is in the Migration but the Controller TwoFactorAuthenticationController is still accessing the field "two_factor_secret_key" (line 103). 

Greetings

**Comment by imrealashu** [comment]
@Destronom I don't think its breaking anything, is it?

**Comment by Destronom** [comment]
@imrealashu just tested it, can't disable TwoFactorAuthentication anymore. In Method disableTwoFactorAuthentication()
should it not be: 
$user->two_factor_provisioned_uri = null; rather than 
$user->two_factor_secret_key = null;
(two_factor_secret_key attribute isn't anymore present in Migration)

**Comment by imrealashu** [comment]
@Destronom I'd suggest go make changes in the source code and eliminate the error. I'll be releasing an update at the earliest.

**Comment by Destronom** [comment]
no problem :-)
