### ISSUE TITLE
Question: How to know if a specific user has two factor authentication enabled?

### ISSUE THREAD

**Issue by andersonpem** [thecodework/two-factor-authentication#52]
Hi. First, thanks for this package. Is there any way of checking if a specific user has 2fa enabled? Depending, if it's enabled or not, the user will be able to access areas of the admin panel that are more sensitive, thus requiring additional security layers.
Thank you.

**Comment by andersonpem** [comment]
Also, can I ask 2FA confirmation before performing an action with a controller? Let's see a hypothetical example of this:
I have a model called BankAccount. I want to make a money transfer to another account. Before doing the actual transaction on the controller the 2FA token would be asked to confirm the action. Then, and only with a valid code, the transaction would be performed and saved on the database. Is that possible or only in the login routine? :)
Thanks.
Thank you very much.

**Comment by ebonit** [comment]
regarding your first question: 
```php
auth()->user()->getAttribute('is_two_factor_enabled');
```

**Comment by ebonit** [comment]
regarding the second question with the uri '/verify-2fa' you are redirected to window where you need to fill in the 2fa code. after verifiction you should be redirected back to the controller where you were before. I never tried this but I think it should work like that.

**Comment by imrealashu** [comment]
Also, the migration has added a column `is_two_factor_enabled` column into the `users` table which you can use anytime to know whether a user has enabled 2FA or not.
